defaults:
  - layer: s4

_name_: sashimi
d_model: 64
n_layers: 8
pool:
  - 4
  - 4
expand: 2
ff: 2
prenorm: True
dropout: 0.0
dropres: 0.0
initializer: null
transposed: True
residual: R
norm: layer
interp: 0
act_pool: null
# l_max: ${dataset.__l_max}

layer:
  l_max: null # Turn off since layers need different lengths
