# Config for the standalone s4.py module for testing purposes
# Should be equivalent to the normal s4.yaml layer
_name_: standalone
d_state: 64
channels: 1
bidirectional: false
activation: gelu
postact: glu
dropout: ${..dropout} # Same as null
mode: nplr
measure: legs
dt_min: 0.001
dt_max: 0.1
lr:
  dt: 0.001
  A: 0.001
  B: 0.001
n_ssm: null
l_max: ${oc.select:dataset.__l_max,null} # Grab dataset length if exists, otherwise set to 1 and kernel will automatically resize
verbose: true
